{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall Observations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Average Satisfaction Rate",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "TDIGEST.TRIMMED_MEAN satisfaction-tdigest 0 1",
     "type": "cli"
    }
   ]
  },
  { "title": "Quantiles Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Customer Satisfaction P30",
   "type": "stat",
   "description": "% of Customers Having a Satisfaction Score less than 30%",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "TDIGEST.CDF satisfaction-tdigest 0.3",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Customer Satisfaction P70",
   "type": "stat",
   "description": "% of Customers Having a Satisfaction Score less than 70%",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "TDIGEST.CDF satisfaction-tdigest 0.7",
     "type": "cli"
    }
   ]
  },
  {
   "title": "Customer Satisfaction P100",
   "type": "stat",
   "description": "% of Customers Having a Satisfaction Score less than 100%",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "TDIGEST.CDF satisfaction-tdigest 1",
     "type": "cli"
    }
   ]
  }
 ]
}